version: "3.9"

services:
  erp:
    build: .
    container_name: ecommerce-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
    expose:
      - "4000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: erp-proxy
    restart: unless-stopped
    ports:
      - "8080:80" # host 8080 → contenedor 80 (Nginx)
      - "443:443"
    volumes:
      - ./nginx.conf.production:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - erp
    networks:
      - web

networks:
  web:
    external: false
